//? Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//? 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//? By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

function fiboEvenSum(n) {
  const fiboSequence = [1, 2];

  let i = 3;

  while (i <= n) {
    fiboSequence.push(i);
    i =
      fiboSequence[fiboSequence.length - 1] +
      fiboSequence[fiboSequence.length - 2];
  }

  const output = fiboSequence
    .filter((val) => (val % 2 === 0 && val <= n ? val : 0))
    .reduce((acc, curr) => acc + curr, 0);

  console.log(output);

  return output;
}

fiboEvenSum(34);

module.exports = fiboEvenSum;

//! ChatGPT's solutions
function fiboEvenSumC(n) {
  let sum = 0;
  let prev = 1;
  let curr = 2;

  while (curr <= n) {
    if (curr % 2 === 0) {
      sum += curr;
    }
    const next = prev + curr;
    prev = curr;
    curr = next;
  }

  console.log(sum);
  return sum;
}

fiboEvenSumC(34);
